### PR TITLE
Update Cilium Details

### PR DESCRIPTION
**Pull request by xmulligan**
Happy to provide references for any of the suggested changes

### CODE REVIEW

**Comment by distributethe6ix** [comment]
Thanks for the PR @xmulligan! 
Can you share some references for the Cilium Service Mesh being GA'd as well as being production ready with any case studies? 

Can you additionally provide some clarification on Multi-cluster Mesh? Does Cilium's cluster-mesh also provide the same foundation for multi-cluster service mesh?

Also, would you be interested in created a section dedicated to the Cilium Service Mesh as one of the days in #70DaysofServiceMesh?

**Comment by xmulligan** [comment]
Sure, it was GA'd in the [last release of Cilium](https://isovalent.com/blog/post/cilium-release-112/) in July. Also based on the most recent Cilium User Survey, people are already running Cilium Service Mesh in production.

For Cluster Mesh, I would check out the blog post above, [the docs](https://docs.cilium.io/en/v1.12/concepts/clustermesh/), and [this lab](https://isovalent.com/labs/cilium-cluster-mesh/) to learn more. What exactly do you mean by "same foundation for multi-cluster service mesh"?

For #70DaysofServiceMesh, I could probably do a day. Do you have a template I could use?

**Comment by shivarm** [comment]
Hey @xmulligan merge conflicts must be resolve

**Comment by xmulligan** [comment]
couldn't resolve the conflicts so changed to #7

**Pull request closed without merging**
